### ISSUE TITLE
Trying to build for Apple Silicon using Clang 16. 

### ISSUE THREAD

**Issue by ntrischi** [fgsfdsfgs/perfect_dark#544]
Attempting to build with Apple clang version 16.0.0 (clang-1600.0.26.4) on Apple silicon: arm64-apple-darwin24.1.0. Any ideas to resolve include errors. 

```
[ 80%] Building C object CMakeFiles/pd.dir/port/src/utils.c.o
[ 81%] Building C object CMakeFiles/pd.dir/port/src/video.c.o
1 warning generated.
[ 81%] Building CXX object CMakeFiles/pd.dir/port/fast3d/gfx_cc.cpp.o
[ 81%] Building CXX object CMakeFiles/pd.dir/port/fast3d/gfx_opengl.cpp.o
In file included from /Users/ntrischi/Downloads/perfect_dark/port/fast3d/gfx_cc.cpp:1:
/Users/ntrischi/Downloads/perfect_dark/port/fast3d/gfx_cc.h:8:10: fatal error: 'compare' file not found
    8 | #include <compare>
      |          ^~~~~~~~~
1 error generated.
make[2]: [ 81%] Building CXX object CMakeFiles/pd.dir/port/fast3d/gfx_sdl2.cpp.o
*** [CMakeFiles/pd.dir/port/fast3d/gfx_cc.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object CMakeFiles/pd.dir/port/fast3d/gfx_pc.cpp.o
/Users/ntrischi/Downloads/perfect_dark/port/fast3d/gfx_pc.cpp:3:10: fatal error: 'cmath' file not found
    3 | #include <cmath>
      |          ^~~~~~~
/Users/ntrischi/Downloads/perfect_dark/port/fast3d/gfx_opengl.cpp:6:10: fatal error: 'map' file not found
    6 | #include <map>
      |          ^~~~~
1 error generated.
make[2]: *** [CMakeFiles/pd.dir/port/fast3d/gfx_pc.cpp.o] Error 1
1 error generated.
make[2]: *** [CMakeFiles/pd.dir/port/fast3d/gfx_opengl.cpp.o] Error 1
make[1]: *** [CMakeFiles/pd.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by fgsfdsfgs** [comment]
> `fatal error: 'cmath' file not found`

This seems to imply your compiler is horribly misconfigured. Not sure how you would fix this, as I'm not well educated on building things on OSX.
In addition is there any reason why you're building with actual Clang instead of using the gcc packages provided in Homebrew?
